// WF-2 card-renderer 생성기: node build-wf2.js > wf2-card-renderer.json
// 입력(Execute Workflow로 전달): {cards, dayType, season, round, raceName, circuitId, dateKst}
// 출력: {urls: [...], dirName, cards 메타}
const fs = require('fs');
const { BROWSERLESS_CRED } = require('./config');
const T = (f) => fs.readFileSync(__dirname + '/../templates/' + f, 'utf8');
const TEMPLATES = {
  css: T('base.css'),
  'session-result': T('session-result.html'),
  'cover-data': T('cover-data.html'),
  'cover-meme': T('cover-meme.html'),
  grid: T('grid.html'),
  'quali-elims': T('quali-elims.html'),
  timetable: T('timetable.html'),
  lineup: T('lineup.html'),
  track: T('track.html'),
  'text-card': T('text-card.html'),
  podium: T('podium.html'),
  stints: T('stints.html'),
  story: T('story.html'),
  'result-full': T('result-full.html'),
  'issue-blocks': T('issue-blocks.html'),
  dotd: T('dotd.html'),
  'story-podium': T('story-podium-full.html'),
};

const PREPARE = [
  'const TPL = ' + JSON.stringify(TEMPLATES) + ';',
  "// 메모리 프리플라이트: 956MB 서버에서 Chromium 렌더링이 VM을 마비시킨 전례가 있어 여유가 없으면 시작하지 않는다.",
  "// 직전 WF-6(밈 이미지 생성)이 n8n 메모리를 100MB 이상 부풀려 놓고 곧바로 반환하지 않으므로,",
  "// 즉시 실패시키지 않고 회복될 때까지 기다린다 — 원인이 일시적 스파이크이기 때문이다.",
  "const MIN_FREE_MB = 220;",
  "const WAIT_MS = 180000;",
  "function availMb() {",
  "  try {",
  "    const mi = require('fs').readFileSync('/proc/meminfo', 'utf8');",
  "    const kb = (k) => { const m = mi.match(new RegExp('^' + k + ':\\\\s+(\\\\d+)', 'm')); return m ? parseInt(m[1]) : 0; };",
  "    return Math.round((kb('MemAvailable') || kb('MemFree')) / 1024);",
  "  } catch (e) { return 0; /* /proc 없으면 통과 */ }",
  "}",
  "let mb = availMb();",
  "if (mb) {",
  "  const deadline = Date.now() + WAIT_MS;",
  "  while (mb < MIN_FREE_MB && Date.now() < deadline) {",
  "    await new Promise((r) => setTimeout(r, 6000));",
  "    mb = availMb();",
  "  }",
  "  if (mb < MIN_FREE_MB) throw new Error('렌더링 중단: 서버 여유 메모리 ' + mb + 'MB (최소 ' + MIN_FREE_MB + 'MB 필요, ' + (WAIT_MS / 1000) + '초 대기 후에도 미달). 잠시 후 재실행하세요.');",
  "}",
  "const input = $input.first().json;",
  "const { cards, dayType, season, round, raceName, dateKst } = input;",
  "if (!cards || !cards.length) throw new Error('cards 비어있음');",
  "if (cards.length > 10) throw new Error('카드 10장 초과: ' + cards.length);",
  "const esc = (s) => String(s == null ? '' : s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');",
  "const fill = (tpl, vars) => tpl.replace(/\\{\\{(\\w+)\\}\\}/g, (_, k) => (k in vars ? vars[k] : ''));",
  "function teamClass(team) {",
  "  const t = String(team || '').toLowerCase();",
  "  if (t.includes('mclaren')) return 't-mclaren';",
  "  if (t.includes('ferrari')) return 't-ferrari';",
  "  if (t.includes('mercedes')) return 't-mercedes';",
  "  if (t.includes('red bull')) return 't-red_bull';",
  "  if (t.includes('aston')) return 't-aston_martin';",
  "  if (t.includes('alpine')) return 't-alpine';",
  "  if (t.includes('williams')) return 't-williams';",
  "  if (t.includes('rb') || t.includes('racing bulls')) return 't-rb';",
  "  if (t.includes('audi') || t.includes('sauber')) return 't-audi';",
  "  if (t.includes('haas')) return 't-haas';",
  "  if (t.includes('cadillac')) return 't-cadillac';",
  "  return 't-default';",
  "}",
  "function listRow(r, metric) {",
  "  return '<div class=\"row' + (r.pos === 1 ? ' p1' : '') + ' ' + teamClass(r.team) + '\">' +",
  "    '<div class=\"pos\">' + r.pos + '</div><div class=\"teambar\"></div>' +",
  "    '<div class=\"drv\"><div class=\"name\">' + esc(r.name) + '</div><div class=\"team\">' + esc(r.team || '') + '</div></div>' +",
  "    '<div class=\"metric\">' + (metric || '') + '</div></div>';",
  "}",
  "function deltaHtml(d) {",
  "  if (d == null) return '<small class=\"delta-flat\">NEW</small>';",
  "  if (d > 0) return '<small class=\"delta-up\">▲' + d + '</small>';",
  "  if (d < 0) return '<small class=\"delta-down\">▼' + -d + '</small>';",
  "  return '<small class=\"delta-flat\">—</small>';",
  "}",
  "function kstLabel(s) {",
  "  const d = new Date(s.replace(' ', 'T') + ':00+09:00');",
  "  const w = ['일','월','화','수','목','금','토'][d.getUTCDay() /* not used */];",
  "  const wd = ['일','월','화','수','목','금','토'];",
  "  const kd = new Date(d.getTime() + 9 * 3600000);",
  "  return (kd.getUTCMonth() + 1) + '월 ' + kd.getUTCDate() + '일 (' + wd[kd.getUTCDay()] + ') ' + String(kd.getUTCHours()).padStart(2, '0') + ':' + String(kd.getUTCMinutes()).padStart(2, '0');",
  "}",
  "// 서킷 배경 자산이 있으면 data URI로 임베드 (browserless가 file:// 차단하므로)",
  "const fs = require('fs');",
  "let bgUri = '';",
  "try {",
  "  const dir = '/data/hooni_speed/assets/backgrounds/' + (input.circuitId || 'none');",
  "  const f = fs.readdirSync(dir).find((x) => /\\.(png|jpe?g)$/i.test(x));",
  "  if (f) bgUri = 'data:image/' + (/\\.png$/i.test(f) ? 'png' : 'jpeg') + ';base64,' + fs.readFileSync(dir + '/' + f).toString('base64');",
  "} catch (e) { /* 배경 없음 — 단색 배경으로 렌더 */ }",
  "const common = { CSS: TPL.css, KICKER: esc(season + ' Round ' + round), DATE: esc(dateKst), NOTE: '공식 결과', BG_URL: bgUri };",
  "// 비고가 비면 구분점도 빼서 '· 날짜'만 남는 모양을 막는다",
  "const fillCard = (tpl, vars) => {",
  "  const note = vars.NOTE == null ? common.NOTE : vars.NOTE;",
  "  const date = vars.DATE == null ? common.DATE : vars.DATE;",
  "  return fill(tpl, { ...vars, NOTE_LINE: note ? note + ' · ' + date : date });",
  "};",
  "function render(card) {",
  "  const d = card.data || {};",
  "  switch (card.template) {",
  "    case 'cover-preview':",
  "    case 'cover-recap':",
  "    case 'cover-data': {",
  "      // 밈 배경(bgImage) > 서킷 배경(bgUri) > 단색 순으로 표지 렌더",
  "      const bg = d.bgImage || bgUri || '';",
  "      const tpl = bg ? TPL['cover-meme'] : TPL['cover-data'];",
  "      return fill(tpl, { ...common, BG_URL: bg, TITLE: esc(d.title || raceName), SUBTITLE: esc(d.subtitle || (d.raceStartKst ? '프리뷰 · 레이스 ' + kstLabel(d.raceStartKst) + ' KST' : '')).replace(/\\n/g, '<br>'), BADGE: d.isSprint ? 'SPRINT WEEK' : '' });",
  "    }",
  "    case 'session-result': {",
  "      const rows = (d.rows || []).slice(0, d.brief ? 5 : 10);",
  "      const html = rows.map((r) => listRow(r, esc(r.time || r.gap || '') + (r.points != null ? ' <small>+' + r.points + 'pt</small>' : ''))).join('');",
  "      return fillCard(TPL['session-result'], { ...common, TITLE: esc(d.session || raceName), SUBTITLE: esc(raceName), ROWS_HTML: html });",
  "    }",
  "    case 'standings': {",
  "      const html = (d.rows || []).slice(0, 10).map((r) => listRow(r, esc(r.points) + 'pt ' + deltaHtml(r.delta))).join('');",
  "      return fillCard(TPL['session-result'], { ...common, TITLE: esc(d.title || ''), SUBTITLE: esc(raceName), ROWS_HTML: html, NOTE: '챔피언십 스탠딩 · 등락은 직전 라운드 대비' });",
  "    }",
  "    case 'grid': {",
  "      const rows = d.rows || [];",
  "      const gshort = (n) => { const p = String(n || '').trim().split(/\\s+/); return p.length > 1 ? p[0][0] + '. ' + p.slice(1).join(' ') : (p[0] || ''); };",
  "      const g = (r) => '<div class=\"g-row' + (parseInt(r.pos) === 1 ? ' p1' : '') + ' ' + teamClass(r.team) + '\"><div class=\"g-pos\">' + r.pos + '</div><div class=\"g-bar\"></div><div class=\"g-name\">' + esc(gshort(r.name)) + '</div></div>';",
  "      // 실제 스타팅 그리드처럼 지그재그로 — 홀수 그리드는 왼쪽, 짝수는 오른쪽 열에 넣는다.",
  "      // 오른쪽 열은 템플릿에서 반 칸 아래로 밀려 어긋난 배치가 된다.",
  "      const odd = rows.filter((r) => parseInt(r.pos) % 2 === 1);",
  "      const even = rows.filter((r) => parseInt(r.pos) % 2 === 0);",
  "      return fillCard(TPL.grid, { ...common, TITLE: esc(d.title || '레이스 그리드'), SUBTITLE: esc(raceName), LEFT_ROWS_HTML: odd.map(g).join(''), RIGHT_ROWS_HTML: even.map(g).join(''), NOTE: esc(d.note || '') });",
  "    }",
  "    case 'quali-elims': {",
  "      const g = (r) => listRow(r, esc(r.q2 || r.q1 || ''));",
  "      // 구간 라벨은 실제 순위에서 뽑는다 — 엔트리 수가 시즌마다 다르다(2026년 22명).",
  "      const range = (arr) => { const p = (arr || []).map((x) => parseInt(x.pos)).filter((n) => !isNaN(n)); return p.length ? 'P' + Math.min(...p) + '–P' + Math.max(...p) : ''; };",
  "      return fillCard(TPL['quali-elims'], { ...common, TITLE: '퀄리파잉 탈락 구간', SUBTITLE: esc(raceName), Q2_LABEL: 'Q2 탈락 ' + range(d.elimQ2), Q1_LABEL: 'Q1 탈락 ' + range(d.elimQ1), Q2_ROWS_HTML: (d.elimQ2 || []).map(g).join(''), Q1_ROWS_HTML: (d.elimQ1 || []).map(g).join('') });",
  "    }",
  "    case 'timetable': {",
  "      const hl = new Set(['퀄리파잉', '레이스', '스프린트']);",
  "      const html = (d.timetable || []).map((t) => '<div class=\"tt-row' + (hl.has(t.session) ? ' hl' : '') + '\"><div class=\"tt-session\">' + esc(t.session) + '</div><div class=\"tt-time\">' + esc(kstLabel(t.startKst)) + '</div></div>').join('');",
  "      return fillCard(TPL.timetable, { ...common, TITLE: '주말 세션 시간표', SUBTITLE: esc(raceName), ROWS_HTML: html, NOTE: '한국 시간(KST) 기준' });",
  "    }",
  "    case 'lineup': {",
  "      const html = Object.entries(d.lineup || {}).map(([team, drs]) => '<div class=\"lu-team ' + teamClass(team) + '\"><div class=\"lu-bar\"></div><div><div class=\"lu-name\">' + esc(team) + '</div><div class=\"lu-drivers\">' + drs.map((x) => esc(x.name)).join(' · ') + '</div></div></div>').join('');",
  "      return fillCard(TPL.lineup, { ...common, TITLE: '드라이버 라인업', SUBTITLE: esc(raceName), TEAMS_HTML: html, NOTE: '시즌 스탠딩 기준' });",
  "    }",
  "    case 'track': {",
  "      return fillCard(TPL.track, { ...common, TITLE: esc(d.nameKr || d.circuitName || ''), SUBTITLE: esc(d.circuitName || ''), LEN: d.lengthKm ? d.lengthKm + ' km' : '-', LAPS: d.laps || '-', LOCATION: esc(d.location || ''), DESC: esc(d.desc || ''), NOTE: '트랙 프로필' });",
  "    }",
  "    case 'result-full': {",
  "      // 22대 전체를 한 장에 — 이름은 'L. Norris' 형태로 줄여 2열에 들어가게 한다",
  "      // 팀명은 줄이면 안 된다 (Aston Martin → A. Martin). shortenNames:false 로 끈다.",
  "      const short = d.shortenNames === false ? ((n) => String(n || '')) : ((n) => { const p = String(n || '').trim().split(/\\s+/); return p.length > 1 ? p[0][0] + '. ' + p.slice(1).join(' ') : (p[0] || ''); });",
  "      const rows = d.rows || [];",
  "      const rf = (r) => '<div class=\"rf-row' + (r.pos === 1 ? ' p1' : '') + (r.out ? ' out' : '') + ' ' + teamClass(r.team) + '\">' +",
  "        '<div class=\"rf-pos\">' + r.pos + '</div><div class=\"rf-bar\"></div>' +",
  "        '<div class=\"rf-name\">' + esc(short(r.name)) + '</div>' +",
  "        '<div class=\"rf-metric\">' + (r.metric || '') + ('delta' in r ? ' ' + deltaHtml(r.delta) : '') + '</div></div>';",
  "      // singleColumn이면 한 열에 세로로 나열한다 (11개 이하일 때만 카드에 들어간다)",
  "      const single = d.singleColumn === true;",
  "      const half = single ? rows.length : Math.ceil(rows.length / 2);",
  "      return fillCard(TPL['result-full'], { ...common, RF_CLASS: single ? 'single' : '', TITLE: esc(d.title || raceName), SUBTITLE: esc(d.subtitle || ''), LEFT_ROWS_HTML: rows.slice(0, half).map(rf).join(''), RIGHT_ROWS_HTML: rows.slice(half).map(rf).join(''), NOTE: esc(d.note || '공식 결과') });",
  "    }",
  "    case 'issue-blocks': {",
  "      const blocks = (d.issues || []).map((x) => '<div class=\"ib\"><div class=\"ib-head\">' + esc(x.head || '') + '</div><div class=\"ib-body\">' + esc(x.body || '') + '</div></div>').join('');",
  "      const chip = d.fastestLap ? '<div class=\"hl-chip\"><span class=\"k\">FASTEST LAP</span><span class=\"v\">' + esc(d.fastestLap.name) + (d.fastestLap.time ? ' · ' + esc(d.fastestLap.time) : '') + '</span></div>' : '';",
  "      const body = blocks || '<div class=\"ib\"><div class=\"ib-body\" style=\"color:#8a8a98\">본문 준비 중 — 발행 전 검수 필요</div></div>';",
  "      return fillCard(TPL['issue-blocks'], { ...common, BG_URL: d.photo && d.photo.url ? d.photo.url : bgUri, TITLE: esc((d.session || '레이스') + ' 이슈'), SUBTITLE: esc(raceName), BLOCKS_HTML: body, CHIP_HTML: chip, CREDIT: d.photo && d.photo.credit ? esc('Photo: ' + d.photo.credit + ' / Pexels') : '', NOTE: '검수 필요' });",
  "    }",
  "    case 'dotd-card': {",
  "      // 드라이버별 액션 이미지를 라운드 번호로 돌려 쓴다 — 같은 수상자여도 매번 다른 포즈가 나간다",
  "      let img = d.image || '';",
  "      if (!img && d.code) {",
  "        try {",
  "          // 맥에서 scp 하면 '._pose.png' 같은 AppleDouble 부산물이 생긴다. .png 로 끝나고",
  "          // 정렬에서 맨 앞이라 그대로 두면 깨진 이미지가 포즈로 선택된다.",
  "          const fl = fs.readdirSync('/data/cards/dotd/' + d.code).filter((x) => x.endsWith('.png') && !x.startsWith('.')).sort();",
  "          if (fl.length) img = 'https://xrp-admin.p-e.kr/hooni-cards/dotd/' + d.code + '/' + fl[round % fl.length];",
  "        } catch (e) { /* 자산 없으면 텍스트만 */ }",
  "      }",
  "      return fillCard(TPL.dotd, { ...common, TITLE: 'Driver of the Day', DRIVER: esc(d.driver || '미발표'), TEAM: esc(d.team || ''), BODY: esc(d.body || '선정 사유 확인 중'), IMG_URL: img, NOIMG: img ? '' : 'noimg', NOTE: esc(d.note || '공식 발표') });",
  "    }",
  "    // tires 는 순위표가 아니라 산문이다. result-full(d.rows) 로 보내면 본문이 통째로 사라진다.",
  "    case 'tires':",
  "    case 'issue':",
  "    case 'dotd': {",
  "      const titles = { tires: '타이어 컴파운드', issue: (d.session || '') + ' 이슈', dotd: '드라이버 오브 더 데이' };",
  "      const body = d.body ? '<p>' + esc(d.body).replace(/\\n+/g, '</p><p>') + '</p>' : '<p style=\"color:#8a8a98\">본문 준비 중 — 발행 전 검수 필요 (LLM 요약 예정)</p>';",
  "      const chip = d.fastestLap ? '<div class=\"hl-chip\"><span class=\"k\">FASTEST LAP</span><span class=\"v\">' + esc(d.fastestLap.name) + (d.fastestLap.time ? ' · ' + esc(d.fastestLap.time) : '') + '</span></div>' : '';",
  "      return fillCard(TPL['text-card'], { ...common, TITLE: esc(titles[card.template] || card.template), SUBTITLE: esc(raceName), BODY_HTML: body, CHIP_HTML: chip, NOTE: card.needsLlm ? '검수 필요' : '공식 결과' });",
  "    }",
  "    case 'podium': {",
  "      const p = d.podium || [];",
  "      const v = {};",
  "      for (let i = 0; i < 3; i++) {",
  "        const x = p[i] || {};",
  "        v['P' + (i + 1) + '_NAME'] = esc(x.name || '-');",
  "        v['P' + (i + 1) + '_TEAM'] = esc(x.team || '');",
  "        v['P' + (i + 1) + '_CLASS'] = teamClass(x.team);",
  "      }",
  "      return fillCard(TPL.podium, { ...common, TITLE: esc((d.season || '') + ' 포디움'), SUBTITLE: esc(d.raceName || raceName), ...v, NOTE: '당시 결과' });",
  "    }",
  "    case 'stints': {",
  "      const rows = d.rows || [];",
  "      let total = 1;",
  "      for (const r of rows) for (const s of r.stints || []) total = Math.max(total, s.to || 0);",
  "      const html = rows.map((r) => {",
  "        const segs = (r.stints || []).map((s) => { const w = Math.max(4, Math.round(((s.to - s.from + 1) / total) * 100)); const cls = 'c-' + String(s.compound || 'unknown').toLowerCase(); const lab = String(s.compound || '?')[0] + ' ' + s.from + '-' + s.to; return '<div class=\"seg ' + cls + '\" style=\"width:' + w + '%\">' + esc(lab) + '</div>'; }).join('');",
  "        return '<div class=\"st-row\"><div class=\"st-drv\">' + r.pos + ' ' + esc(r.code || '') + '</div><div class=\"st-bar\">' + segs + '</div></div>';",
  "      }).join('');",
  "      return fillCard(TPL.stints, { ...common, TITLE: esc(d.title || '타이어 전략'), SUBTITLE: esc(raceName), ROWS_HTML: html, NOTE: 'OpenF1 스틴트' });",
  "    }",
  "    default:",
  "      throw new Error('알 수 없는 템플릿: ' + card.template);",
  "  }",
  "}",
  "// 스토리(9:16)는 피드 카드와 별도로 렌더 — 캐러셀에 섞이면 안 되므로 isStory 표시",
  "function renderStory(st) {",
  "  const d = st.data || {};",
  "  let bg = '';",
  "  if (d.bgFile && /^https?:\\/\\//.test(d.bgFile)) {",
  "    bg = d.bgFile; // HTTP URL — Chromium이 직접 로드 (대용량 base64 임베드 회피)",
  "  } else if (d.bgFile) {",
  "    try { bg = 'data:image/png;base64,' + fs.readFileSync(d.bgFile).toString('base64'); } catch (e) { bg = bgUri; }",
  "  } else { bg = bgUri; }",
  "  if (st.template === 'story-podium' && (d.podium || []).length) {",
  "    // 순위는 그림이 아니라 오버레이로 넣는다 — AI가 그린 숫자에 의존하면 틀린 정보가 나간다",
  "    const TEAM_HEX = { mclaren: '#ff8000', ferrari: '#e8002d', mercedes: '#00d7b6', 'red bull': '#3671c6', 'aston martin': '#229971', alpine: '#ff87bc', williams: '#64c4ff', rb: '#6692ff', audi: '#00e701', sauber: '#00e701', haas: '#b6babd', cadillac: '#e6c14d' };",
  "    const hex = (t) => { const k = String(t || '').toLowerCase(); for (const n in TEAM_HEX) if (k.includes(n)) return TEAM_HEX[n]; return '#8a8a98'; };",
  "    const rows = d.podium.map((r) => '<div class=\"sp-row' + (r.pos === 1 ? ' p1' : '') + '\">' +",
  "      '<div class=\"sp-pos\">' + r.pos + '</div>' +",
  "      '<div class=\"sp-bar\" style=\"--team:' + hex(r.team) + '\"></div>' +",
  "      '<div class=\"sp-who\"><div class=\"sp-name\">' + esc(r.name) + '</div><div class=\"sp-team\">' + esc(r.team || '') + '</div></div>' +",
  "      '<div class=\"sp-gap\">' + esc(r.gap || '') + '</div></div>').join('');",
  "    return fillCard(TPL['story-podium'], { CSS: TPL.css, BG_URL: bg, KICKER: esc(season + ' ROUND ' + round + ' · RACE'), GP_NAME: esc(d.title || raceName), SUBTITLE: esc(d.subtitle || ''), ROWS_HTML: rows, CTA: esc(d.cta || '전체 결과는 피드에서 👉') });",
  "  }",
  "  return fillCard(TPL.story, { ...common, BG_URL: bg, TITLE: esc(d.title || raceName), SUBTITLE: esc(d.subtitle || ''), CTA: esc(d.cta || '자세한 내용은 피드에서 👉') });",
  "}",
  "// 실행 식별자를 폴더명에 넣는다 — 같은 GP를 여러 번 돌리면 만료된 옛 실행의 Cleanup이",
  "// 새 실행의 카드까지 지워버린 적이 있다 (폴더명이 같아서 구분 불가).",
  "//",
  "// 단, 수정 재렌더는 같은 base 를 유지해야 한다. Cleanup 은 base 와 base+'-rev*' 를 함께",
  "// 지우는데, 재렌더마다 base 가 바뀌면 이전 회차 폴더가 정리되지 않고 남는다.",
  "// 새 실행(스케줄·재요청)은 입력에 baseDirName 이 없으므로 여전히 새 식별자를 받는다.",
  "const runTag = String($execution.id || Date.now()).slice(-6);",
  "const baseDirName = input.baseDirName || season + '-r' + round + '-' + dayType + '-' + runTag;",
  "const dirName = baseDirName + (input.dirSuffix || '');",
  "// 본문이 실제로 비었는지 판정한다. needsLlm 은 'LLM을 쓰는 카드'라는 고정 선언이라",
  "// 성공·실패와 무관하게 항상 켜져 있어 경고 신호로 쓸 수 없다 (2026-08-20 빈 카드 발행).",
  "function isBodyEmpty(card) {",
  "  const d = card.data || {};",
  "  switch (card.template) {",
  "    case 'issue-blocks': return !(d.issues || []).length;",
  "    case 'tires': case 'issue': return !d.body;",
  "    case 'dotd': return !d.body;",
  "    case 'dotd-card': return !d.driver || !d.body;",
  "    case 'result-full': case 'session-result': case 'standings': return !(d.rows || []).length;",
  "    case 'podium': return !(d.podium || []).length;",
  "    default: return false;",
  "  }",
  "}",
  "const items = cards.map((card, i) => ({ json: { html: render(card), dirName, baseDirName, fileName: 'card-' + (i + 1) + '-' + card.type + '.png', cardIndex: i + 1, cardType: card.type, needsLlm: card.needsLlm || [], bodyEmpty: isBodyEmpty(card), isStory: false, viewport: { width: 1080, height: 1350 } } }));",
  "if (input.story) {",
  "  items.push({ json: { html: renderStory(input.story), dirName, baseDirName, fileName: 'story.png', cardIndex: items.length + 1, cardType: 'story', needsLlm: input.story.needsLlm || [], isStory: true, viewport: { width: 1080, height: 1920 } } });",
  "}",
  "return items;",
].join('\n');

const nodes = [];
const connections = {};
let uid = 0;
function n(name, type, parameters, pos, typeVersion, extra) {
  uid += 1;
  nodes.push({ parameters, type: 'n8n-nodes-base.' + type, typeVersion: typeVersion || 1, position: pos, id: 'd' + String(uid).padStart(7, '0') + '-0000-4000-8000-000000000000', name, ...(extra || {}) });
  return name;
}
function c(from, to) {
  connections[from] = connections[from] || { main: [[]] };
  connections[from].main[0].push({ node: to, type: 'main', index: 0 });
}

n('When Executed by Another Workflow', 'executeWorkflowTrigger', {}, [0, 0]);
n('Prepare Cards', 'code', { jsCode: PREPARE }, [220, 0], 2);
n(
  'Mkdir',
  'code',
  { jsCode: "const fs = require('fs');\nfs.mkdirSync('/data/cards/' + $input.first().json.dirName, { recursive: true });\nreturn $input.all();" },
  [440, 0],
  2
);
n(
  'Render PNG',
  'httpRequest',
  {
    method: 'POST',
    // browserless 기본 작업 제한은 120초. 956MB·2코어에서 1080×1920 렌더가 이를 넘겨
    // 연결이 끊기므로 요청 단위로 300초까지 허용한다.
    url: 'http://browserless:3000/screenshot?timeout=300000',
    authentication: 'genericCredentialType',
    genericAuthType: 'httpQueryAuth',
    sendBody: true,
    specifyBody: 'json',
    jsonBody: "={{ JSON.stringify({ html: $json.html, viewport: $json.viewport, options: { type: 'png', clip: { x: 0, y: 0, width: $json.viewport.width, height: $json.viewport.height } } }) }}",
    options: {
      timeout: 320000,
      batching: { batch: { batchSize: 1, batchInterval: 8000 } },
      response: { response: { responseFormat: 'file', outputPropertyName: 'data' } },
    },
  },
  [660, 0],
  4.2,
  {
    retryOnFail: true,
    maxTries: 4,
    waitBetweenTries: 45000,
    credentials: { httpQueryAuth: BROWSERLESS_CRED },
  }
);
n(
  'Save PNG',
  'code',
  {
    jsCode: [
      "const fs = require('fs');",
      "const prep = $('Prepare Cards').all().map((i) => i.json);",
      "const items = $input.all();",
      "if (items.length !== prep.length) throw new Error('렌더 결과 개수 불일치: ' + items.length + ' vs ' + prep.length);",
      "for (let i = 0; i < items.length; i++) {",
      "  const buf = await this.helpers.getBinaryDataBuffer(i, 'data');",
      "  if (!buf || !buf.length) throw new Error('빈 PNG: item ' + i);",
      "  fs.writeFileSync('/data/cards/' + prep[i].dirName + '/' + prep[i].fileName, buf);",
      "}",
      "return [{ json: { saved: items.length } }];",
    ].join('\n'),
  },
  [880, 0],
  2
);
n(
  'Collect URLs',
  'code',
  {
    jsCode: [
      "const input = $('When Executed by Another Workflow').first().json;",
      "const prep = $('Prepare Cards').all().map((i) => i.json);",
      "const base = 'https://xrp-admin.p-e.kr/hooni-cards/';",
      "const feed = prep.filter((p) => !p.isStory);",
      "const story = prep.find((p) => p.isStory);",
      "const urls = feed.map((p) => base + p.dirName + '/' + p.fileName);",
      "const storyUrl = story ? base + story.dirName + '/' + story.fileName : null;",
      "const needsReview = prep.filter((p) => p.needsLlm && p.needsLlm.length).map((p) => p.cardIndex);",
      "// emptyCards 는 needsReview 와 다르다 — 실제로 본문이 빈 카드만 담는다. 상시 켜지지 않으므로 신호가 된다.",
      "const emptyCards = prep.filter((p) => p.bodyEmpty).map((p) => p.cardIndex);",
      "return [{ json: { ...input, urls, storyUrl, dirName: prep[0].dirName, baseDirName: prep[0].baseDirName, cardCount: feed.length, needsReview, emptyCards } }];",
    ].join('\n'),
  },
  [1100, 0],
  2
);
c('When Executed by Another Workflow', 'Prepare Cards');
c('Prepare Cards', 'Mkdir');
c('Mkdir', 'Render PNG');
c('Render PNG', 'Save PNG');
c('Save PNG', 'Collect URLs');

process.stdout.write(
  JSON.stringify(
    {
      id: 'HooniWF2Rndr0001',
      name: 'HooniSpeed WF-2 card-renderer',
      nodes,
      connections,
      settings: { executionOrder: 'v1', timezone: 'Asia/Seoul', errorWorkflow: 'HooniWFErr00001' },
      active: false,
    },
    null,
    2
  ) + '\n'
);
